spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/toy?serverTimezone=UTC&characterEncoding=UTF-8
    password: '1234'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            clientId: 583659906956-u1tct97j3veg48brpo84l6m1gao97005.apps.googleusercontent.com           # (1)
            clientSecret: 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  # (2)
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace